const furnitureArtwork: Record<string, string> = {
  rack: '/assets/furniture/sunday-rack.png',
  'shoe-shelf': '/assets/furniture/candy-shoe-shelf.png',
  'bag-stand': '/assets/furniture/ribbon-bag-stand.png',
  table: '/assets/furniture/accessory-table.png',
  'wall-rack': '/assets/furniture/pastel-double-rack.png',
  'shoe-cabinet': '/assets/furniture/cloud-shoe-cabinet.png',
  'bag-cabinet': '/assets/furniture/blush-bag-cabinet.png',
  'lux-rack': '/assets/furniture/gold-arch-rack.png',
  'couture-rack': '/assets/furniture/moon-couture-rack.png',
  'glass-showcase': '/assets/furniture/crystal-led-bag-showcase.png',
  'global-showcase': '/assets/furniture/global-flagship-showcase.png',
  'atelier-island': '/assets/furniture/atelier-accessory-island.png',
  'jewel-shoe-wall': '/assets/furniture/jewel-shoe-gallery.png',
  flowers: '/assets/furniture/blush-flower-vase.png',
  plant: '/assets/furniture/small-olive-tree.png',
  mannequin: '/assets/furniture/poet-mannequin.png',
  'monstera-plant': '/assets/furniture/ceramic-monstera.png',
  beanbag: '/assets/furniture/marshmallow-beanbag.png',
  'vinyl-player': '/assets/furniture/melody-player.png',
  'coffee-corner': '/assets/furniture/takeaway-coffee-counter.png',
  counter: '/assets/furniture/checkout-counter.png',
  sofa: '/assets/furniture/marshmallow-sofa.png',
  'atelier-rug': '/assets/furniture/atelier-pastel-rug.png',
  'heart-rug': '/assets/furniture/heart-fur-rug.png',
  'checkered-rug': '/assets/furniture/retro-checkered-rug.png',
  'coquette-mirror': '/assets/furniture/coquette-bow-mirror.png',
  'wavy-mirror': '/assets/furniture/neon-wavy-mirror.png',
  mirror: '/assets/furniture/muse-arch-mirror.png',
  'tulip-lamp': '/assets/furniture/tulip-floor-lamp.png',
  'perfume-table': '/assets/furniture/perfume-stone-table.png',
  'champagne-sofa': '/assets/furniture/champagne-lounge-sofa.png',
  'runway-mannequin': '/assets/furniture/runway-spotlight-mannequin.png',
  fitting: '/assets/furniture/pink-curtain-fitting-room.png',
  'blush-blinds': '/assets/furniture/blush-blinds.png',
  'botanical-print': '/assets/furniture/botanical-blush-print.png',
  'shoe-sketch-print': '/assets/furniture/kitten-heel-print.png',
  'parfum-print': '/assets/furniture/parfum-paris-print.png',
  'runway-print': '/assets/furniture/runway-dress-print.png',
  'fashion-print': '/assets/furniture/fashion-muse-prints.png',
  'gallery-print': '/assets/furniture/gallery-lovely-print.png',
  'ribbon-sign': '/assets/furniture/welcome-ribbon-sign.png',
  'lightbox-sign': '/assets/furniture/fashion-club-lightbox.png',
  'neon-sign': '/assets/furniture/fashion-neon-sign.png',
};

export const allFurnitureArtwork = Object.freeze([...new Set(Object.values(furnitureArtwork))]);

export function externalFurnitureArtwork(art: string): string | undefined {
  return furnitureArtwork[art];
}
